-- Cách 1: TÌM OUTLIERS SỬ DỤNG PHƯƠNG PHÁP BOX PLOT (IQR) -> 8 outliers
SELECT Q1 - 1.5 * IQR AS min_value,
Q3 + 1.5 * IQR AS max_value
FROM(
SELECT
percentile_cont(0.25) WITHIN GROUP (ORDER BY QUANTITYORDERED) as Q1,
percentile_cont(0.75) WITHIN GROUP (ORDER BY QUANTITYORDERED) as Q3,
percentile_cont(0.75) WITHIN GROUP (ORDER BY QUANTITYORDERED) - 
percentile_cont(0.25) WITHIN GROUP (ORDER BY QUANTITYORDERED) as IQR
from SALES_DATASET_RFM_PRJ) AS a)

SELECT * FROM SALES_DATASET_RFM_PRJ
WHERE QUANTITYORDERED < (SELECT min_value FROM twt_min_max_value)
OR QUANTITYORDERED > (SELECT max_value FROM twt_min_max_value)

-- CÁCH 2: TÌM OUTLIERS SỬ DỤNG PHƯƠNG PHÁP Z SCORE -> 14 outliers
WITH CTE AS(
SELECT *, 
(SELECT AVG(QUANTITYORDERED) FROM SALES_DATASET_RFM_PRJ) AS AVG,
(SELECT STDDEV(QUANTITYORDERED) FROM SALES_DATASET_RFM_PRJ) 
AS STDDEV
FROM SALES_DATASET_RFM_PRJ)
SELECT *, (QUANTITYORDERED - AVG)/ STDDEV AS Z_SCORE 
FROM CTE
WHERE ABS((QUANTITYORDERED - AVG)/STDDEV) > 3

-- XỬ LÝ GIÁ TRỊ NGOẠI LAI
-- CÁCH 1: UPDATE BẰNG GIÁ TRỊ TRUNG BÌNH CỦA DATASET ĐÓ
WITH CTE AS(
SELECT *, 
(SELECT AVG(QUANTITYORDERED) FROM SALES_DATASET_RFM_PRJ) AS AVG,
(SELECT STDDEV(QUANTITYORDERED) FROM SALES_DATASET_RFM_PRJ) 
AS STDDEV
FROM SALES_DATASET_RFM_PRJ), 
TWT_OUTLIER AS(
SELECT *, (QUANTITYORDERED - AVG)/ STDDEV AS Z_SCORE 
FROM CTE
WHERE ABS((QUANTITYORDERED - AVG)/STDDEV) > 3)

UPDATE SALES_DATASET_RFM_PRJ
SET QUANTITYORDERED = (SELECT AVG(QUANTITYORDERED)
FROM SALES_DATASET_RFM_PRJ)
WHERE QUANTITYODERED IN (SELECT QUANTITYORDERD FROM TWT_OUTLIER)

-- CÁCH 2: DELETE CÁC GIÁ TRỊ ĐÓ KHỎI DATASET
DELETE FROM SALES_DATASET_RFM_PRJ
WHERE QUANTITYORDERED IN (SELECT QUANTITYORDERED FROM TWT_OUTLIER)
