ALTER TABLE SALES_DATASET_RFM_PRJ
ADD COLUMN QTR_ID INT,
ADD COLUMN MONTH_ID INT,
ADD COLUMN YEAR_ID INT

UPDATE SALES_DATASET_RFM_PRJ
SET QTR_ID = EXTRACT(QUARTER FROM ORDERDATE),
MONTH_ID = EXTRACT(MONTH FROM ORDERDATE),
YEAR_ID = EXTRACT(YEAR FROM ORDERDATE)
