-- Check NULL/BLANK (‘’)  ở các trường: ORDERNUMBER, QUANTITYORDERED, PRICEEACH, ORDERLINENUMBER, SALES, ORDERDATE.
SELECT *
FROM SALES_DATASET_RFM_PRJ
WHERE 
    ORDERNUMBER IS NULL 
    OR QUANTITYORDERED IS NULL 
    OR PRICEEACH IS NULL 
    OR ORDERLINENUMBER IS NULL 
    OR SALES IS NULL 
    OR ORDERDATE IS NULL 
