-- Chuyển đổi kiểu dữ liệu phù hợp cho các trường ( sử dụng câu lệnh ALTER) 
SELECT * FROM SALES_DATASET_RFM_PRJ;

ALTER TABLE SALES_DATASET_RFM_PRJ
ALTER COLUMN ORDERNUMBER TYPE NUMERIC USING (trim(ORDERNUMBER):: NUMERIC);

ALTER TABLE SALES_DATASET_RFM_PRJ
ALTER COLUMN QUANTITYORDERED TYPE NUMERIC USING (trim(QUANTITYORDERED):: NUMERIC);

ALTER TABLE SALES_DATASET_RFM_PRJ
ALTER COLUMN PRICEEACH TYPE NUMERIC USING (trim(PRICEEACH):: NUMERIC);

ALTER TABLE SALES_DATASET_RFM_PRJ
ALTER COLUMN ORDERLINENUMBER TYPE NUMERIC USING (trim(ORDERLINENUMBER):: NUMERIC);

ALTER TABLE SALES_DATASET_RFM_PRJ
ALTER COLUMN SALES TYPE NUMERIC USING (trim(SALES):: NUMERIC); 

ALTER TABLE SALES_DATASET_RFM_PRJ
ALTER COLUMN ORDERDATE TYPE TIMESTAMP USING (trim(ORDERDATE):: TIMESTAMP);

ALTER TABLE SALES_DATASET_RFM_PRJ
ALTER COLUMN MSRP TYPE NUMERIC USING (trim(MSRP):: NUMERIC);
